"""Generate the root layout, the dashboard, and the frontend container files.

The dashboard used to open with `list(1, 0)` per entity and render
`data.total` as a headline count. Keyset pagination has no total — a count is
the full scan the new pagination exists to avoid (CODEGEN_CONTRACT §7) — so
the cards link into each collection instead of asserting a number nothing can
supply.
"""

from __future__ import annotations

from forge.targets.base import GeneratedFile
from forge.targets.nextjs.context import FrontendContext


def generate_layout(ctx: FrontendContext) -> list[GeneratedFile]:
    return [
        _root_layout(ctx),
        _dashboard(ctx),
        _dockerfile(ctx),
        _dockerignore(ctx),
    ]


def _root_layout(ctx: FrontendContext) -> GeneratedFile:
    domain_title = ctx.ir.domain.replace("_", " ").title()

    if ctx.auth is not None:
        # The shell is a client component: it needs the current path to leave
        # the sign-in page outside the gate, and the gate itself has to run in
        # the browser to hold the in-memory access token.
        body = """        <AppShell>{children}</AppShell>"""
        shell_import = 'import { AppShell } from "@/components/AppShell";'
    else:
        body = """        <div className="flex min-h-screen bg-gray-50">
          <AppSidebar />
          <main className="min-w-0 flex-1 p-8">{children}</main>
        </div>"""
        shell_import = 'import { AppSidebar } from "@/components/AppSidebar";'

    content = f'''import "./globals.css";
{shell_import}

export const metadata = {{
  title: "{domain_title}",
  description: "Generated by Specora",
}};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="en">
      <body>
{body}
      </body>
    </html>
  );
}}
'''
    return GeneratedFile(
        path="frontend/src/app/layout.tsx",
        content=content,
        provenance=f"domain/{ctx.ir.domain}",
    )


def _dashboard(ctx: FrontendContext) -> GeneratedFile:
    domain_title = ctx.ir.domain.replace("_", " ").title()

    cards = "\n".join(
        f'''        <Link
          href="{view.url}"
          className="block rounded-lg border bg-white p-6 shadow-sm hover:shadow-md"
        >
          <h3 className="text-lg font-semibold">{view.page.title or view.component}</h3>
          <p className="mt-1 text-sm text-gray-500">{_card_description(view)}</p>
        </Link>'''
        for view in ctx.views
    )

    content = f"""import Link from "next/link";

export default function Dashboard() {{
  return (
    <div>
      <h1 className="mb-2 text-2xl font-bold">{domain_title}</h1>
      <p className="mb-6 text-gray-500">Dashboard</p>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
{cards}
      </div>
    </div>
  );
}}
"""
    return GeneratedFile(
        path="frontend/src/app/page.tsx",
        content=content,
        provenance=f"domain/{ctx.ir.domain}",
    )


def _card_description(view) -> str:
    """A one-line description for a dashboard card, escaped for JSX text."""
    text = view.entity.description or f"Browse {view.page.name.replace('_', ' ')}"
    # `{` and `}` open a JSX expression; `<` opens a tag.
    return text.replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;")


def _dockerfile(ctx: FrontendContext) -> GeneratedFile:
    content = """FROM node:20-slim AS builder
WORKDIR /app

# `npm ci`, not `npm install`. install re-resolves every caret range and quietly
# rewrites the lockfile when the two disagree, so the image built from a given
# set of contracts depended on the day it was built. ci installs the lockfile
# exactly, verifies each package against its recorded integrity hash, and exits
# non-zero if the lockfile is absent or has drifted from package.json — the
# failure is the feature.
#
# --ignore-scripts because otherwise this line runs lifecycle scripts from 143
# packages as root, with a network, inside the build. Next.js needs none: its
# swc binaries and sharp ship prebuilt as per-platform optional dependencies,
# already hash-pinned by the same lockfile.
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund
COPY . .

# Next.js substitutes NEXT_PUBLIC_* into the client bundle during `next build`,
# so this has to arrive as a build argument. Passing it at run time instead —
# which is what docker-compose.yml used to do — leaves the fallback in
# src/lib/config.ts baked into the JavaScript the browser runs, and the
# override is silently ignored. The value must be an address the *browser* can
# reach, never a compose-internal service name.
ARG NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
# The build runs as root; the app does not need to.
RUN useradd --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
"""
    return GeneratedFile(
        path="frontend/Dockerfile.frontend",
        content=content,
        provenance=f"domain/{ctx.ir.domain}",
    )


def _dockerignore(ctx: FrontendContext) -> GeneratedFile:
    content = """node_modules/
.next/
.git/
*.md
.env
.env.*
"""
    return GeneratedFile(
        path="frontend/.dockerignore",
        content=content,
        provenance=f"domain/{ctx.ir.domain}",
    )
