# forge/targets/nextjs/gen_layout.py
"""Generate root layout, dashboard, and Docker files."""
from __future__ import annotations

from forge.ir.model import DomainIR
from forge.targets.base import GeneratedFile


def _to_pascal(name: str) -> str:
    return "".join(p.capitalize() for p in name.split("_"))


def generate_layout(ir: DomainIR) -> list[GeneratedFile]:
    return [
        _generate_root_layout(ir),
        _generate_dashboard(ir),
        _generate_dockerfile(ir),
        _generate_dockerignore(ir),
    ]


def _generate_root_layout(ir: DomainIR) -> GeneratedFile:
    domain_title = ir.domain.replace("_", " ").title()

    content = f'''import "./globals.css";
import {{ AppSidebar }} from "@/components/AppSidebar";

export const metadata = {{
  title: "{domain_title}",
  description: "Generated by Specora",
}};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen bg-gray-50">
          <AppSidebar />
          <main className="flex-1 p-8">
            {{children}}
          </main>
        </div>
      </body>
    </html>
  );
}}
'''
    return GeneratedFile(path="frontend/src/app/layout.tsx", content=content, provenance=f"domain/{ir.domain}")


def _generate_dashboard(ir: DomainIR) -> GeneratedFile:
    domain_title = ir.domain.replace("_", " ").title()
    entity_map = {e.fqn: e for e in ir.entities}

    cards = []
    imports = ['"use client";', 'import { useEffect, useState } from "react";', 'import Link from "next/link";']

    for page in ir.pages:
        entity = entity_map.get(page.entity_fqn)
        if not entity:
            continue
        cls = _to_pascal(entity.name)
        route = page.route.strip("/")
        imports.append(f'import {{ {page.name} }} from "@/lib/api";')
        cards.append(f'''
        <Link href="/{route}" className="block rounded-lg border bg-white p-6 shadow-sm hover:shadow-md transition-shadow">
          <h3 className="text-lg font-semibold">{page.title or cls}</h3>
          <p className="text-3xl font-bold mt-2">{{counts.{page.name} ?? "—"}}</p>
          <p className="text-sm text-gray-500 mt-1">total records</p>
        </Link>''')

    count_fetches = []
    for page in ir.pages:
        count_fetches.append(f'      const {page.name}Data = await {page.name}.list(1, 0);')
        count_fetches.append(f'      newCounts.{page.name} = {page.name}Data.total || 0;')

    cards_str = "\n".join(cards)
    fetches_str = "\n".join(count_fetches)
    imports_str = "\n".join(imports)

    content = f'''{imports_str}

export default function Dashboard() {{
  const [counts, setCounts] = useState<any>({{}});

  useEffect(() => {{
    async function load() {{
      const newCounts: any = {{}};
{fetches_str}
      setCounts(newCounts);
    }}
    load();
  }}, []);

  return (
    <div>
      <h1 className="text-2xl font-bold mb-2">{domain_title}</h1>
      <p className="text-gray-500 mb-6">Dashboard</p>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
{cards_str}
      </div>
    </div>
  );
}}
'''
    return GeneratedFile(path="frontend/src/app/page.tsx", content=content, provenance=f"domain/{ir.domain}")


def _generate_dockerfile(ir: DomainIR) -> GeneratedFile:
    content = """FROM node:20-slim AS builder
WORKDIR /app
COPY package.json ./
RUN npm install --prefer-offline --no-audit --no-fund
COPY . .
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
"""
    return GeneratedFile(path="frontend/Dockerfile.frontend", content=content, provenance=f"domain/{ir.domain}")


def _generate_dockerignore(ir: DomainIR) -> GeneratedFile:
    content = """node_modules/
.next/
.git/
*.md
"""
    return GeneratedFile(path="frontend/.dockerignore", content=content, provenance=f"domain/{ir.domain}")
