"""Base generator interface — all target generators implement this.

Generators are the final stage of the Forge pipeline. They consume
the Intermediate Representation (DomainIR) and produce code files
for a specific target (TypeScript, FastAPI, PostgreSQL, etc.).

The key constraint: generators import ONLY forge.ir.model.
They never import the parser, validator, or raw contract types.
This ensures target-agnosticism — the IR is the contract between
the compiler and generators.

Every generated file includes a provenance header that identifies:
  - Which contract(s) produced it
  - When it was generated
  - That it should NOT be hand-edited

Usage:
    from forge.targets.base import BaseGenerator, GeneratedFile

    class MyGenerator(BaseGenerator):
        def name(self) -> str:
            return "my_target"

        def generate(self, ir: DomainIR) -> list[GeneratedFile]:
            files = []
            for entity in ir.entities:
                files.append(GeneratedFile(
                    path="output/types.ts",
                    content="...",
                    provenance=entity.fqn,
                ))
            return files
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone

from forge.ir.model import DomainIR
from forge.provenance import provenance_source_line


@dataclass
class GeneratedFile:
    """A single file produced by a generator.

    Attributes:
        path: Relative path for the output file (e.g., "backend/models.py").
        content: The full file content including provenance header.
        provenance: FQN(s) of the contract(s) that produced this file.
    """

    path: str
    content: str
    provenance: str


class BaseGenerator(ABC):
    """Abstract base class for all target generators.

    Subclasses implement name() and generate(). The Forge CLI discovers
    generators by name and calls generate() with the compiled DomainIR.
    """

    @abstractmethod
    def name(self) -> str:
        """The generator's identifier (used in --target flag).

        Returns:
            Short lowercase name (e.g., "typescript", "fastapi", "postgres").
        """
        ...

    @abstractmethod
    def generate(self, ir: DomainIR) -> list[GeneratedFile]:
        """Generate code files from the IR.

        Args:
            ir: The compiled DomainIR containing all domain definitions.

        Returns:
            List of GeneratedFile objects ready to be written to disk.
        """
        ...


def provenance_header(
    language: str,
    provenance: str,
    description: str = "",
) -> str:
    """Generate a provenance header for a generated file.

    The header identifies the file as generated code and warns
    against hand-editing. It includes the source contract FQN
    and generation timestamp.

    Args:
        language: Comment style — "python", "typescript", "sql", "yaml".
        provenance: Source contract FQN(s).
        description: Optional description of what this file contains.

    Returns:
        Multi-line comment string to prepend to generated files.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    comment_styles = {
        "python": ("#", "#", "#"),
        "typescript": ("//", "//", "//"),
        "sql": ("--", "--", "--"),
        "yaml": ("#", "#", "#"),
    }
    start, mid, end = comment_styles.get(language, ("//", "//", "//"))

    lines = [
        f"{start} {'=' * 70}",
        f"{mid} @generated — DO NOT EDIT",
        f"{mid}",
        f"{mid} This file was generated by Specora Forge from contract specifications.",
        f"{mid} Any manual changes will be overwritten on the next generation.",
        f"{mid}",
        f"{mid} {provenance_source_line(provenance)}",
        f"{mid} Source: {provenance}",
        f"{mid} Generated: {timestamp}",
    ]
    if description:
        lines.append(f"{mid}")
        lines.append(f"{mid} {description}")
    lines.append(f"{end} {'=' * 70}")
    lines.append("")

    return "\n".join(lines)
